- name: Put profile on remote
  copy: 
    src: "../files/addProfile.txt"
    dest: /home/centos/addProfile.txt
    owner: centos 
    group: wheel

- name: create script log directory
  file:
    path: /var/log/script
    state: directory
    mode: 755

- name: Set script command.
  shell: "touch /etc/profile || cat ../files/addProfile.txt > /etc/profile"

- name: add a new user
  user: name={{ item.name }} state={{ item.state }} group={{ item.group }} password={{ item.password }}
  with_items: 
    - { "name":"{{MG_username}}", "state":"present", "group":"wheel", "password":"{{MG_password}}" }
    - { "name":"{{tech_username}}", "state":"present", "group":"wheel", "password":"{{tech_password}}" }
    - { "name":"{{OP_username}}", "state":"present", "group":"users", "password":"{{OP_password}}" }

- name: mkdir .ssh
  file: dest="{{ item.dest }}/.ssh/" state=directory owner={{ item.owner }}
  with_items: 
    - { "dest":"{{MG_homedir}}", "owner":"{{MG_username}}" }
    - { "dest":"{{tech_homedir}}", "owner":"{{tech_username}}" }
    - { "dest":"{{OP_homedir}}", "owner":"{{OP_username}}" }

- name: copy a public key file to remote
  copy: src={{ item.src }} dest={{ item.dest }} mode=600
  with_items:
    - { "src":"../files/trashMG.pub", "dest":"{{MG_homedir}}/.ssh/authorized_keys" }
    - { "src":"../files/tech-user.pub", "dest":"{{tech_homedir}}/.ssh/authorized_keys" }
    - { "src":"../files/operator.pub", "dest":"{{OP_homedir}}/.ssh/authorized_keys" }

- name: Modify tech-user's home directory owner(true)
  file:
    path: /home/tech-user/
    owner: tech-user
    recurse: yes
    state: directory

- name: get zabbix agent rpm file.
  get_url:
    url: http://repo.zabbix.com/zabbix/3.2/rhel/7/x86_64/zabbix-agent-3.2.6-1.el7.x86_64.rpm
    dest: "/tmp/zabbix-agent-3.2.6-1.el7.x86_64.rpm"

- name: install zabbix agent.
  yum: name=/tmp/zabbix-agent-3.2.6-1.el7.x86_64.rpm

- name: put zabbix-agent.conf on remote
  copy: 
    src: "../files/zabbix_agentd.conf"
    dest: /etc/zabbix/zabbix_agentd.conf
    owner: zabbix
    group: zabbix


- name: Add sudo authority for zabbix user
  lineinfile:
    dest: /etc/sudoers
    backup: yes
    line: 'zabbix ALL=(root) NOPASSWD: ALL'

- name: not require tty on sudo
  lineinfile:
    dest: /etc/sudoers
    backup: yes
    line: 'Defaults:zabbix !requiretty'

- name: Add SELinux permit rule.
  shell: setenforce 0

- name: Start zabbix-agent service
  systemd:
    name: zabbix-agent
    enabled: yes
    state: restarted
